title: "krass.codes"
description: >-
  A blog for Swift code examples and experiments. Sometimes non-Swift stuff too.
github_username:  KrassCodes
minimal_mistakes_skin: "dark"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Krass Iankov"
  avatar   : "/assets/bio-photo.png"
  # bio      : "Software engineer 🛠"
  # location : "Remote"
  # links:
  #   - label: "YouTube channel"
  #     icon: "fab fa-youtube"
  #     url: "https://youtube.com/channel/UCSMxuZP6KUb_i9F-K1LAtrw"
  #   - label: "GitHub"
  #     icon: "fab fa-github"
  #     url: "https://github.com/KrassCodes"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
#      author_profile: true
      show_date: true
      read_time: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

theme: jekyll-theme-cayman
